CREATE TABLE IF NOT EXISTS Customers (
	CUST_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	CUST_FIRSTNAME VARCHAR(230) NOT NULL,
	CUST_LASTNAME VARCHAR(230) NOT NULL,
	CUST_BIRTHDAY DATE,
	CUST_GENDER CHAR(1) NOT NULL,
	CUST_ADDRESS VARCHAR(250),
	CUST_CITY VARCHAR(250),
	CUST_POSTCODE VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS Accounts (
	ACC_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ACC_NUMBER VARCHAR(13) NOT NULL,
	ACC_OWNER INT NOT NULL,
	ACC_DATE_CREATED DATE DEFAULT NOW(),
	ACC_BALANCE BIGINT NOT NULL,
	FOREIGN KEY (ACC_OWNER)
	REFERENCES customers(cust_id)
);

CREATE  TABLE IF NOT EXISTS Transactions (
	TRS_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	TRS_FROM_ACCOUNT INT NOT NULL,
	TRS_DATE DATE NOT NULL,
	TRS_AMOUNT INT NOT NULL,
	TRS_TYPE VARCHAR(2) NOT NULL,
	FOREIGN KEY (TRS_FROM_ACCOUNT)
	REFERENCES accounts(acc_id)
);

CREATE  TABLE IF NOT EXISTS Transaction_Transfer (
	TRST_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	TRS_ID INT NOT NULL,
	TRS_TO_ACCOUNT INT NOT NULL,
	TRS_STATUS VARCHAR(1) NOT NULL,
	FOREIGN KEY (TRS_ID)
	REFERENCES transactions(trs_id),
	FOREIGN KEY (TRS_TO_ACCOUNT)
	REFERENCES accounts(acc_id)
);

SELECT  acc_owner, cust_firstname, cust_lastname , count(acc_owner) AS total_account FROM accounts a
JOIN customers c ON acc_owner = cust_id
GROUP BY acc_owner, cust_firstname, cust_lastname ;

SELECT *, a.acc_number FROM transactions t
JOIN accounts a  ON a.acc_id = t.trs_from_account 
JOIN customers c ON a.acc_owner = c.cust_id
WHERE c.cust_firstname = 'John' AND c.cust_lastname = 'Michael'
ORDER BY a.acc_number ASC
	NULLS LAST,
	t.trs_date ASC;
